### ISSUE TITLE
package.json is missing socket.io

### ISSUE THREAD

**Issue by halkeand** [AntonioErdeljac/chatTutorial#1]
Hey, thanks for the tutorial and repo ! The `socket.io` backend npm package is missing in the package.json. 😄

**Comment by AntonioErdeljac** [comment]
Hi, Im not sure what you mean, i can see it here
`
{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.2",
    "socket.io": "^2.0.4"
  }
}
`

**Comment by AntonioErdeljac** [comment]
Oh I get it, the package.json outside backend & frontend folder shouldn't have existed, please do cd frontend && npm i, cd backend && npm i :D
